// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"TextPicture","status":true,"description":"Displays text as a picture.","parameters":{}},
{"name":"PluginSalvarGPT","status":true,"description":"Adds Import Save & Export Save buttons to the title menu (with auto-save before export).","parameters":{}}
];
